### ISSUE TITLE
can not compile to css file in version 1.6

### ISSUE THREAD

**Issue by fadesky** [jdiehl/brackets-less-autocompile#81]
can not compile to css file in version 1.6 when save less file.

status bar shows errors:
Uncaught TypeError: Cannot read property 'line' of undefined
/language/CodeInspection.js:423

**Comment by jdiehl** [comment]
Can you please provide some more information? What file are you trying to compile? Does a manual compile work? Are there any errors on the Brackets console (you can access it via Debug > Show Developer Tools)

**Comment by NikosEfthias** [comment]
i have very same issue nothing happens when i hit save details are in photos 
![screenshot from 2016-03-01 23-08-52](https://cloud.githubusercontent.com/assets/9097437/13440376/c9ce7f82-e002-11e5-8706-dc19393df209.png) for the first photo the file name is called `test.less`

![screenshot from 2016-03-01 23-11-27](https://cloud.githubusercontent.com/assets/9097437/13440415/f46165ca-e002-11e5-95b2-86d4e07a5333.png)
![screenshot from 2016-03-01 23-11-58](https://cloud.githubusercontent.com/assets/9097437/13440435/0ac50268-e003-11e5-8aa6-6113eb0eb5c0.png)

**Comment by jdiehl** [comment]
Does the plugin work without the `// out: ./new.css` prefix? Can you please check the Brackets console for any errors?

**Comment by NikosEfthias** [comment]
@jdiehl  theres no error specific to brackets auto less

**Comment by jdiehl** [comment]
Not sure how to help you then...
