### ISSUE TITLE
.less is not updating .css

### ISSUE THREAD

**Issue by kcollins-marton** [jdiehl/brackets-less-autocompile#87]
Hi,
I'm very new to all this, but I love using less. I am very frustrated now as my .less file is not updating my .css file, so my changes aren't being made. I am obliged to work in the css file. 
It was working when I first started the project I'm working on.
Any idea what the problem could be? I have shut down, restarted several times, but unfortunately that doesn't change anything.
Thanks for any help you could give me.

**Comment by jdiehl** [comment]
Can you check the Brackets command line for any errors? (Go to Debug -> Show Developer Tools and click on Console)

**Comment by kcollins-marton** [comment]
Thanks for your answer! It seems I have many errors, see attached screenshot...
![less](https://cloud.githubusercontent.com/assets/17066728/15215452/ab1bf33e-1820-11e6-9a0f-f9b8e3d8006c.jpg)

**Comment by jdiehl** [comment]
Can you scroll down a bit?

**Comment by kcollins-marton** [comment]
Thank you so much for your time and your help. Here is the bottom part of the errors.
![less2](https://cloud.githubusercontent.com/assets/17066728/15321254/4ec2999e-1c03-11e6-8b0e-675331bf5b21.jpg)

**Comment by jdiehl** [comment]
I don't see any problems with the plugin or the node connection, so it should be working. Not sure what could be going wrong...

**Comment by kcollins-marton** [comment]
OK. Thanks for checking for me. Maybe I just need to reinstall everything.... Thanks again!

**Comment by transparentDesign** [comment]
Sometimes it may just a syntax error?

At the bottom right of the screen: if you have this warning symbol...
![screen shot 2017-06-28 at 14 25 41](https://user-images.githubusercontent.com/25198535/27639350-d2fa107a-5c0d-11e7-8d10-920bfd6aa595.png)

...rather than this 'everything is good' symbol...
![screen shot 2017-06-28 at 14 25 50](https://user-images.githubusercontent.com/25198535/27639430-16db82ba-5c0e-11e7-98b7-13af4f04500e.png)


 then click the warning symbol and it'll show you the error(s).
